# Generated by Django 3.2 on 2021-04-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoboticsClub_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClubCategory',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='what_we_do',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='who_we_are',
        ),
        migrations.AddField(
            model_name='aboutcateory',
            name='what_we_do',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutcateory',
            name='who_we_are',
            field=models.TextField(blank=True),
        ),
    ]
