# Generated by Django 3.2 on 2021-04-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamandEvent', '0002_auto_20210409_2307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
